import { leetcodeItem as item } from "../common.js";
const parent = {
  id: "10.2",
  path: "./docs/Algorithm/leetcode/"
};

export const leetcode = {
  id: "10.2",
  label: "leetcode题解",
  children: [
    item(parent, 1, "两数之和"),
    item(parent, 3, "无重复字符的最长子串"),
    item(parent, 5, "最长回文子串"),
    item(parent, 7, "整数反转"),
    item(parent, 9, "回文数"),
    item(parent, 13, "罗马数字转整数"),
    item(parent, 14, "最长公共前缀"),
    item(parent, 15, "三数之和"),
    item(parent, 16, "最接近的三数之和"),
    item(parent, 17, "电话号码的字母组合"),
    item(parent, 20, "有效的括号"),
    item(parent, 21, "合并两个有序链表"),
    item(parent, 26, "删除排序数组中的重复项"),
    item(parent, 27, "移除元素"),
    item(parent, 28, "实现 strStr()"),
    item(parent, 33, "搜索旋转排序数组"),
    item(parent, 35, "搜索插入位置"),
    item(parent, 36, "有效的数独"),
    item(parent, 39, "组合总和"),
    item(parent, 40, "组合总和 II"),
    item(parent, 41, "缺失的第一个正数"),
    item(parent, 43, "字符串相乘"),
    item(parent, 44, "通配符匹配"),
    item(parent, 49, "字母异位词分组"),
    item(parent, 50, "Pow(x,n)"),
    item(parent, 53, "最大子序和"),
    item(parent, 64, "最小路径和"),
    item(parent, 66, "加一"),
    item(parent, 67, "二进制求和"),
    item(parent, 69, "x 的平方根"),
    item(parent, 70, "爬楼梯"),
    item(parent, 76, "最小覆盖子串"),
    item(parent, 77, "组合"),
    item(parent, 84, "柱状图中最大的矩形"),
    item(parent, 88, "合并两个有序数组"),
    item(parent, 94, "二叉树中序遍历"),
    item(parent, 95, "不同的二叉搜索树 II"),
    item(parent, 96, "不同的二叉搜索树"),
    item(parent, 100, "相同的树"),
    item(parent, 101, "对称二叉树"),
    item(parent, 102, "二叉树的层序遍历"),
    item(parent, 104, "二叉树的最大深度"),
    item(parent, 105, "从前序与中序遍历序列构造二叉树"),
    item(parent, 106, "从中序与后序遍历序列构造二叉树"),
    item(parent, 107, "二叉树的层次遍历 II"),
    item(parent, 108, "将有序数组转换为二叉搜索树"),
    item(parent, 109, "有序链表转换二叉搜索树"),
    item(parent, 110, "平衡二叉树"),
    item(parent, 111, "二叉树的最小深度"),
    item(parent, 112, "路径总和"),
    item(parent, 114, "二叉树展开为链表"),
    item(parent, 116, "填充每个节点的下一个右侧节点指针"),
    item(parent, 117, "填充每个节点的下一个右侧节点指针 II"),
    item(parent, 118, "杨辉三角"),
    item(parent, 119, "杨辉三角 II"),
    item(parent, 120, "三角形最小路径和"),
    item(parent, 121, "买卖股票的最佳时机"),
    item(parent, 122, "买卖股票的最佳时机 II"),
    item(parent, 125, "验证回文串"),
    item(parent, 130, "被围绕的区域"),
    item(parent, 133, "克隆图"),
    item(parent, 136, "只出现一次的数字"),
    item(parent, 144, "二叉树的前序遍历"),
    item(parent, 145, "二叉树的后序遍历"),
    item(parent, 146, "LRU 缓存机制"),
    item(parent, 150, "逆波兰表达式求值"),
    item(parent, 152, "乘积最大子数组"),
    item(parent, 155, "最小栈"),
    item(parent, 159, "至多包含两个不同字符的最长子串"),
    item(parent, 167, "两数之和 II - 输入有序数组"),
    item(parent, 169, "多数元素"),
    item(parent, 170, "两数之和 III - 数据结构设计"),
    item(parent, 189, "旋转数组"),
    item(parent, 198, "打家劫舍"),
    item(parent, 200, "岛屿数量"),
    item(parent, 202, "快乐数"),
    item(parent, 205, "同构字符串"),
    item(parent, 206, "反转链表"),
    item(parent, 207, "课程表"),
    item(parent, 209, "长度最小的子数组"),
    item(parent, 213, "打家劫舍 II"),
    item(parent, 215, "数组中的第 K 个最大元素"),
    item(parent, 216, "组合总和 III"),
    item(parent, 217, "存在重复元素"),
    item(parent, 219, "存在重复元素 II"),
    item(parent, 221, "最大正方形"),
    item(parent, 226, "翻转二叉树"),
    item(parent, 235, "二叉搜索树的最近公共祖先"),
    item(parent, 236, "二叉树的最近公共祖先"),
    item(parent, 238, "除自身以外数组的乘积"),
    item(parent, 243, "最短单词距离"),
    item(parent, 249, "移位字符串分组"),
    item(parent, 256, "粉刷房子"),
    item(parent, 257, "二叉树的所有路径"),
    item(parent, 268, "缺失数字"),
    item(parent, 270, "最接近的二叉搜索树值"),
    item(parent, 276, "栅栏涂色"),
    item(parent, 279, "完全平方数"),
    item(parent, 283, "移动零"),
    item(parent, 287, "寻找重复数"),
    item(parent, 288, "单词的唯一缩写"),
    item(parent, 297, "二叉树的序列化与反序列化"),
    item(parent, 300, "最长上升子序列"),
    item(parent, 303, "区域和检索 - 数组不可变"),
    item(parent, 309, "最佳买卖股票时机含冷冻期"),
    item(parent, 311, "稀疏矩阵的乘法"),
    item(parent, 332, "重新安排行程"),
    item(parent, 336, "回文对"),
    item(parent, 337, "打家劫舍 III"),
    item(parent, 343, "整数拆分"),
    item(parent, 347, "前 K 个高频元素"),
    item(parent, 349, "两个数组的交集"),
    item(parent, 350, "两个数组的交集 II"),
    item(parent, 354, "俄罗斯套娃信封问题"),
    item(parent, 368, "最大整除子集"),
    item(parent, 378, "有序矩阵中第K小的元素"),
    item(parent, 380, "常数时间插入、删除和获取随机元素"),
    item(parent, 392, "判断子序列"),
    item(parent, 394, "字符串解码"),
    item(parent, 401, "二进制手表"),
    item(parent, 404, "左叶子之和"),
    item(parent, 414, "第三大的数"),
    item(parent, 415, "字符串相加"),
    item(parent, 424, "替换后的最长重复字符"),
    item(parent, 437, "路径总和 III"),
    item(parent, 448, "找到所有数组中消失的数字"),
    item(parent, 454, "四数相加 II"),
    item(parent, 459, "重复的子字符串"),
    item(parent, 471, "编码最短长度的字符串"),
    item(parent, 485, "最大连续1的个数"),
    item(parent, 486, "预测赢家"),
    item(parent, 491, "递增子序列"),
    item(parent, 494, "目标和"),
    item(parent, 501, "二叉搜索树中的众数"),
    item(parent, 509, "斐波那契数"),
    item(parent, 529, "扫雷游戏"),
    item(parent, 532, "数组中的 K-diff 数对"),
    item(parent, 542, "01 矩阵"),
    item(parent, 560, "和为k的子数组"),
    item(parent, 561, "数组拆分 I"),
    item(parent, 566, "重塑矩阵"),
    item(parent, 572, "另一个树的子树"),
    item(parent, 581, "最短无序连续子数组"),
    item(parent, 599, "两个列表的最小索引总和"),
    item(parent, 605, "种花问题"),
    item(parent, 624, "数组列表中的最大距离"),
    item(parent, 628, "三个数的最大乘积"),
    item(parent, 647, "回文子串"),
    item(parent, 652, "寻找重复的子树"),
    item(parent, 657, "机器人能否返回原点"),
    item(parent, 673, "最长递增子序列的个数"),
    item(parent, 680, "验证回文字符串 Ⅱ"),
    item(parent, 687, "最长同值路径"),
    item(parent, 696, "计数二进制子串"),
    item(parent, 705, "设计哈希集合"),
    item(parent, 706, "设计哈希映射"),
    item(parent, 718, "最长重复子数组"),
    item(parent, 725, "打开转盘锁"),
    item(parent, 733, "图像渲染"),
    item(parent, 739, "每日温度"),
    item(parent, 740, "删除与获得点数"),
    item(parent, 771, "宝石与石头"),
    item(parent, 779, "第K个语法符号"),
    item(parent, 783, "二叉搜索树节点最小距离"),
    item(parent, 785, "判断二分图"),
    item(parent, 821, "新21点"),
    item(parent, 841, "钥匙和房间"),
    item(parent, 873, "最长的斐波那契子序列的长度"),
    item(parent, 918, "环形子数组的最大和"),
    item(parent, 974, "和可被 K 整除的子数组"),
    item(parent, 983, "最低票价"),
    item(parent, 990, "等式方程的可满足性"),
    item(parent, 1004, "最大连续1的个数 III"),
    item(parent, 1014, "最佳观光组合"),
    item(parent, 1025, "除数博弈"),
    item(parent, 1027, "最长等差数列"),
    item(parent, 1028, "从先序遍历还原二叉树"),
    item(parent, 1055, "形成字符串的最短路径"),
    item(parent, 1095, "山脉数组中查找目标值"),
    item(parent, 1371, "每个元音包含偶数次的最长子字符串"),
    item(parent, 1388, "3n 块披萨"),
    item(parent, 1431, "拥有最多糖果的孩子"),
    item(parent, "i29", "顺时针打印矩阵"),
    item(parent, "i46", "把数字翻译成字符串"),
    item(parent, "i51", "数组中的逆序对"),
    item(parent, "i56", "I. 数组中数字出现的次数"),
    item(parent, "i64", "求 1+2+…+n")
  ]
};
